### ISSUE TITLE
No active Transaction was found for ID

### ISSUE THREAD

**Issue by orendin** [Particular/NServiceBus.Transport.AzureServiceBus#48] opened 2019-02-06 16:16 UTC
**Describe the bug**
I've checked the other open transaction issues and the problems don't seem to match our issue.
Our issue only seems to arise after a prolonged "rest" period of no messages being received / sent. We are not quite sure how long this period is. It seems like some underlying session or connection is closed.

We get the following log entry in our seq log every now and then:
**Immediate Retry is going to retry message 'e74f0d16-27c1-4608-bb61-e1ddbf40110a' because of an exception:** 
SourceContext: NServiceBus.RecoverabilityExecutor

```
    System.InvalidOperationException: No active Transaction was found for ID 'txn:9e879b829a0e446d97d6ac7625862833:9_G5'. The Transaction may have timed out or attempted to span multiple top-level entities such as Queue or Topic. The server Transaction timeout is: 00:02:00. Reference:fbcf536a-d67a-4a0f-8fb7-7532b8360f78, TrackingId:44c4b18d00000014000024ca5c5832b5_G5_B7, SystemTracker:SOMSYSTEMNAME:Queue:SOMEQUEUENAME, Timestamp:2019-02-04T12:40:21
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.Invoke(ITransportReceiveContext context, Func`2 next)
   at NServiceBus.MainPipelineExecutor.Invoke(MessageContext messageContext)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.ProcessMessage(Task`1 receiveTask)
```
This is logged as "Information", not error. Funnily, the immediate retry then succeeds. Any any subsequent messages succeed as well.

We have the following setup (simplified).
* two publisher endpoints subscribing to a common topic (to share events)
* two sender endpoints sending messages to either of the first two publisher endpoints via a direct send.

```
  var transport = _endpointConfiguration.UseTransport<AzureServiceBusTransport>();

                transport.ConnectionString(EndpointOptions.MessageBusConnectionString);
                transport.TopicName(EndpointOptions.TopicName);

                // cut the event name if it is larger than 50 which is the limit of asb
                transport.RuleNameShortener(eventName => eventName.Split('.').Last());
```

The process is as follows:
1. A sender endpoint (e.g. third party system) sends a Message to a publisher endpoint via `endpointInstance.SendMessage(someMessage, publisherEndpointName);`. This is successful.
2. The publisher endpoint receives the Message and handles it, and, inside the handler, makes a publish on the context. This seems to fail, causing the Handler to be retried and fully executed again, succeeding the second time around without issue. Here's the Handle code:
```
 public async Task Handle(AMessage message, IMessageHandlerContext context)
        {
               //...ommited for brevity

                var integrationEvent = new SomeIntegrationEvent(aggregate.Id, code, contact);
                await context.Publish(integrationEvent);

               //...ommited for brevity
        }
```
3. Subscribers on the topic (e.g. publisher endpoint 2) receive the Event after the retry successfully publishes onto the Topic.

**To Reproduce**
I'm afraid our issue only seems to arise after a prolonged "rest" period of no messages being received / sent. We are not quite sure how long this period is. It seems like some underlying session or connection is closed. It might be re-created with the first immediate retry, then it continues to work for some time.
I'm wondering if the Azure Service Bus kills open connections / transactions and NSB doesn't handle that or something similar?

Or maybe we have our configuration wrong? Or maybe there's nothing we can do about it?

**Expected behavior**
No recurring Transaction exception should be occurring.

**Versions:**
 - NuGet package: 1.0.1
 - OS: Azure AppService
 - .NET Version dotnet core 2.2

Azure App Services are always on, isolated.

**Comment by SeanFeldman** [comment] 2019-02-06 17:42
@orendin is transport transaction mode you're using for this endpoint [`SendsAtomicWithReceive`](https://docs.particular.net/transports/transactions#transactions-transport-transaction-sends-atomic-with-receive)?

`SomeIntegrationEvent` and `AMessage` are covered by a transaction when a handler is executed under endpoint in `SendsAtomicWithReceive` mode. 

Are there any additional logs in the log file around the time when this issue happens? How often have you seen it taking place? 

I would suggest to take TrackingId `44c4b18d00000014000024ca5c5832b5_G5_B7` and open a support case with Microsoft in parallel to see what is logged on the broker side. If you could, please share it with us via support (reference this issue when raising a support case at https://particular.net/support).

**Comment by orendin** [comment] 2019-02-07 09:19
@SeanFeldman thanks for the quick reply!
I am not sure what transaction mode is used. We don't explicitly configure anything and I couldn't find the default in the doc (even though your doc is usually fantastic). What is the default?

I crawled through all the logs we have, but could not find any other entries with errors around that time. AppInsights. We have only just now installed and configured ServiceControl and have yet to see another instance of the issue arise.
We are currently doing active development and don't have a prod environment, yet. So we only see this problem around once a day.

I just realised that I don't have permissions to open a support case via the azure portal. I'll see if I can get the subscription owner to file a support case (which might take a while...).

**Comment by SeanFeldman** [comment] 2019-02-07 15:25
@orendin could you please either raise a support case at https://particular.net/support) pointing to this thread or send me your information at sean (dot) feldman (at) particular (dot) net? I'll need a few details from you that should not be shared here. Thanks.

**Comment by joshuataylor** [comment] 2019-02-08 01:17
We have also been experiencing this, and have lodged a bug with Particular & Azure regarding this.

**Comment by SeanFeldman** [comment] 2019-02-08 17:28
**Update**: we're investigating this issue and working with Microsoft team to find out what could be the cause. Thank you for your patience and stay tuned for updates. In case this is blocking your project, please contact our support (https://particular.net/support) and mention this public issue. Thank you.

**Comment by joshuataylor** [comment] 2019-02-12 05:30
I'm currently receiving this on a consistent basis, I start sending in a lot of events and my handlers will start showing this.

Is there some timeline (I know it's not a NSB issue :)), as ASB is almost unuseable for us at this point.

**Comment by SeanFeldman** [comment] 2019-02-12 05:34
> Is there some timeline (I know it's not a NSB issue :))

Unfortunately, it's not entirely under our control @joshuataylor.
Can you share a repro with us? Or raise an issue with the [client team](https://github.com/Azure/azure-service-bus-dotnet/issues) to outline what steps to take to reproduce it. They won't take NServiceBus code, so if you'd like, I could help you to convert that into native code.

**Comment by joshuataylor** [comment] 2019-02-12 11:28
Managed to get this to reproduce, see https://github.com/joshuataylor/NsbHandlerReproduction . Basically sending a lot of messages makes it hit, today I was getting "unlucky", where almost every message my Handler would send would fail.

I'll try and also get this to work with the ASB transport for .NET, as Azure support is being unhelpful.

**Comment by SeanFeldman** [comment] 2019-02-13 23:32
I've used your repro (with some slight changes) @joshuataylor and this are my findings so far:

- Happens on both Standard and Premium tier
- Default prefetch count (10) - fails ❌ 
  - Prefetch count set to 2 - fails ❌ 
  - Prefetch count set to 1 - works ✔️ 

My next step would be to have this repro w/o NSB code.

**Comment by SeanFeldman** [comment] 2019-02-14 23:55
Some more update - tried to disable prefetch altogether and set concurrency to 1, still got an exception (1 for 1200 sent messages). This is good as I can rule out concurrency and prefetch and repro it natively.
Important to have a large number of messages for testing to repro this issue.

**Comment by joshuataylor** [comment] 2019-02-15 00:33
@SeanFeldman , I get this a lot more when working from the office/home, where I'm ~50ms away from ASB. Can you try on a different region, and see if it occurs more? (Dumb theory).

**Comment by SeanFeldman** [comment] 2019-02-15 04:11
I'm testing outside of Azure data centre. Don't think proximity has anything to do with it.
With concurrency set to 1 and no prefetch, for 2K messages I've seen 6 exceptions. At this point I'll switch to trying and repro it natively.

**Comment by SeanFeldman** [comment] 2019-02-18 19:25
@joshuataylor I'm working on converting the repro to the native ASB client code only. Will update the issue once some details emerge.

**Comment by jgoyvaerts** [comment] 2019-04-04 09:58
Hey @SeanFeldman , Any update on this? Also experiencing this issue.

**Comment by SeanFeldman** [comment] 2019-04-04 18:35
@jgoyvaerts not yet. The focus was on #51 as it was a critical issue with a substantial impact on production environments. This issue is next in line.

While investigation is taking place, note that NServiceBus recoverability is addressing this error. Failed messages will be retried and succeed.

**Comment by joshuataylor** [comment] 2019-06-05 06:36
We're still seeing this on production. We're starting to move away from NSB due to these issues.

**Comment by orendin** [comment] 2019-06-05 14:11
A note from our side on this. We were still running into this issue on a regular basis and sometimes had undesired side effects (performance being one of them).
We moved to use ReceiveOnly mode, since we have to be idempotent anyway.
Using the following got completely rid of the problem:

`transport.Transactions(TransportTransactionMode.ReceiveOnly);`

That might not be a feasible solution for every use case, though. We were never able to pinpoint the underlying issue and have not spent any more time figuring out why this is happening. Not sure if anyone here in the thread has seen any official (helpful) statement from Microsoft.

**Comment by SeanFeldman** [comment] 2019-06-10 21:21
Quick update: narrowing down NServiceBus repro shows that this is unrelated to the pre-fetch count. While reviewing our implementation of the ASB transport, there's a prefetch bug (#49) that was not entirely fixed, it's still not the cause of the issue. The problem is likely connected to the concurrency. Concurrency greater than one to be more specific. The next step will be to identify where exactly this bug is happening (ASB client, NServiceBus, etc). I'll follow up on the issue to provide regular updates.

**Comment by SeanFeldman** [comment] 2019-06-11 23:26
Update: 
- Native repro has been completed https://github.com/SeanFeldman/TransactionIssueRepro
- A client public issue was raised https://github.com/Azure/azure-sdk-for-net/issues/6540

Native repro code (in case anyone is interested) is at https://github.com/SeanFeldman/TransactionIssueRepro, `TransactionIssueRepro.sln` to load the sender and receiver.

**Comment by SeanFeldman** [comment] 2019-06-19 23:34
Update:
- Microsoft has [acknowledged](https://github.com/Azure/azure-sdk-for-net/issues/6540#event-2425751977) this is a bug.
- Service Bus team is working on the fix.

**Comment by gomateus** [comment] 2019-07-24 10:18
Hey guys! Any updates regarding the fix?

**Comment by SeanFeldman** [comment] 2019-07-24 10:27
@gomateus please follow the Microsoft issue https://github.com/Azure/azure-sdk-for-net/issues/6540. Once Microsoft releases the fix, the issue with the transport will be automatically sorted out as it's a server-side issue. Thank you

**Comment by SeanFeldman** [comment] 2019-08-14 19:19
The server-side issue was fixed and deployed. My tests show that the exception is no longer thrown by the broker. Going to close this issue. Please follow up on the [service issue](https://github.com/Azure/azure-sdk-for-net/issues/6540) in case exception is still happening, specifying the region and the namespace used to reproduce it.

Thank you for the patience and help with sorting this out.

**Closed by SeanFeldman** 2019-08-14 19:19 UTC
