### ISSUE TITLE
Transaction error

### ISSUE THREAD

**Issue by ekjuanrejon** [Particular/NServiceBus.Transport.AzureServiceBus#28] opened 2018-11-29 13:01 UTC
_(Editors note): This is caused by Azure/azure-service-bus-dotnet#615_

Hello 

Now and then I get the following errors. This happens when a surge of events arrive at the queue.

2018-11-29 12:29:30.062 WARN  NServiceBus.Transport.AzureServiceBus.MessagePump Recoverability failed for message with ID 1038f638-88d1-447c-99ab-278ed100eecd. The message will be retried. Exception details: System.InvalidOperationException: Local transactions are not supported with other resource managers/DTC.
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)
   at NServiceBus.DelayedRetryExecutor.Retry(IncomingMessage message, TimeSpan delay, TransportTransaction transportTransaction)
   at NServiceBus.RecoverabilityExecutor.DeferMessage(DelayedRetry action, ErrorContext errorContext)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.ProcessMessage(Task`1 receiveTask)

**Comment by yvesgoeleven** [comment] 2018-11-29 13:16
Interesting, we got a similar report yesterday, but have not yet been able to determine what the cause is.

Azure Service Bus client does indeed not allow to send in a transaction scope where any other resource is enlisted already and that appears to be happening here for some reason.

We already have code in place to prevent this from happening, we inject a transaction scope suppress behavior into the pipeline, https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/develop/src/Transport/Receiving/TransactionScopeSuppressBehavior.cs
, so that any other transaction scope used in your handlers is separated from the one wrapping the receive operations https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/develop/src/Transport/Receiving/MessagePump.cs#L199

But for some reason this still seems to happen, so we need to dig a bit deeper to understand why another transaction scope is somehow bypassing that suppress scope and therefore mix with our receive scope trying to promote the transaction to DTC.

What other transactional resource are you using (e.g. a database connection)? Are you using that resource in places other then an nservicebus handler? Do you have any customizations to the pipeline?

Can you by any chance send us a reproduction that we can further investigate?

**Comment by SeanFeldman** [comment] 2018-11-29 16:57
@ekjuanrejon do you by any chance have anywhere in your code creation of a transaction scope using [`TransactionScopeOption.Required`](https://referencesource.microsoft.com/#System.Transactions/System/Transactions/TransactionScope.cs,7651ec7ad4ade52d,references) option?

**Comment by ekjuanrejon** [comment] 2018-11-29 20:18
Hello,

@SeanFeldman I am not using the transaction scope. The setup is basically very simple.

I have component A is is publishing events and component B is subscribing to those events and pushing into to couchbase db.

It seems to work fine for a couple of days. After of couple of days it gives the warning above and no messages gets process. Gets stuck on that loop and messages just get queued up. I have to restart the service and everything will start to work fine again

**Comment by SeanFeldman** [comment] 2018-11-29 20:43
It would be really good for us to be able to run exactly the same code as you do to identify what's going wrong. Any possibility to create a simple repro involving the components you're using that fails with this exception?

**Comment by ekjuanrejon** [comment] 2018-11-29 20:47
@SeanFeldman 

I can show the code that we are using. We can have a phone call. I think you are in Canada and I am in Dublin. 

This app is running in .net core and in kubernetes. The only issue we have is that with the transaction scope.

**Comment by SeanFeldman** [comment] 2018-11-29 20:51
@ekjuanrejon sounds good. How about raising a support case via https://particular.net/support and mention this GH issue. One of us will set up a call.

**Comment by SeanFeldman** [comment] 2018-12-05 05:45
I have successfully reproduced this issue using .NET Core on Windows and Linux, when a handler is trying to create a new transaction scope using `TransactionScopeOption.Suppress` option. This does work fine with .NET Framework, which leads me to think that the behavior for transaction scope with suppress option is either broken under .NET Core or is not the same and the ASB client doesn't handle it properly. Will raise an issue with the client for Microsoft to start investigation.

**Comment by SeanFeldman** [comment] 2018-12-05 18:08
@ekjuanrejon we've investigated internally and found that this is not transport issue, nor ASB client. The problem is most likely with another library you're using that has a dependency on System.Data.SqlClient.
To execute transaction wrapped in a suppressed scope (what the transport is doing), System.Data.SqlClient version has to be 4.5.0 or higher. Could you please check if you directly or indirectly the version of System.Data.SqlClient is 4.5.0 or later? I suspect it's not.

**Comment by ekjuanrejon** [comment] 2018-12-05 18:59
Hello I am not using System.Data.SqlClient. I am using couchbase which is document store. Only reason using NServicebus is not subscribe to events. This issue happens when a surge of events are received. The app only work luke foe two days after that it throws that warning and stops consuming messages

**Comment by SeanFeldman** [comment] 2018-12-05 19:01
@ekjuanrejon any chance we can get on a call? Trying to resolve this via GitHub issue is not going to work.

**Comment by ekjuanrejon** [comment] 2018-12-05 21:46
Sure. Are you available at the moment?

**Comment by SeanFeldman** [comment] 2018-12-05 21:47
Ping me directly at sean.feldman @ particular.net and I'll set up a call.

**Comment by joshuataylor** [comment] 2018-12-06 03:32
Also seeing this, it'll randomly surface, and can show either in minutes or days (as above).

**Comment by SeanFeldman** [comment] 2018-12-06 05:51
@ekjuanrejon @joshuataylor @chrisvfabio please note that there's a bug in the ASB .NET Standard client when it comes to ambient transaction and `RetryPolicy`,  triggered by *connectivity issues*.

I've raised an [issue](https://github.com/Azure/azure-service-bus-dotnet/issues/615) with the Messaging team. Once it's fixed and released, we'll update our transport.

**Comment by joshuataylor** [comment] 2018-12-06 05:58
What exactly are connectivity issues? We faced it within Azure when in the same region, as well as different regions, as well as remotely.

**Comment by joshuataylor** [comment] 2018-12-06 06:07
Would this be why we are also seeing slow performance? When we have a lot of messages, it takes a while for them to move onto the next message (even with a higher prefetch), this also happens within Azure and outside of Azure (though obviously ASB is hosted).

**Comment by SeanFeldman** [comment] 2018-12-06 06:11
@joshuataylor I cannot say anything about performance. Connectivity issues could be transient errors or throttling. The point is that this exception is hiding what's really happening and it's caused by RetryPolicy that has a bug when an ambient transaction is found. Which is the case with `SendsAtomicWithReceive`. With `ReceiveOnly` transport transaction mode there's no ambient transaction and this exception would not be thrown, running retry policy correctly.

**Comment by KarlHC** [comment] 2018-12-06 09:44
I have the same error, but not intermittent, it is always thrown when I enable the Outbox functionality.  Without the Outbox enabled, everything works fine.  

I am not doing **anything** in my handler, just to test it.  But when I enable the Outbox ==> System.InvalidOperationException: Local transactions are not supported with other resource managers/DTC.

**Comment by SeanFeldman** [comment] 2018-12-06 15:18
Trying to solve everyone's variant of what seems to be a related problem would be extremely hard on a public issue w/o diving into more details. It could be a combination of this issue with something else. It could be a whole different problem. With ASB client, or how we use it. Let's sort this out.

@KarlHC @joshuataylor could you please support cases for your issues? When opening a support case, please refer to this issue. Thank you 🙂

**Comment by SeanFeldman** [comment] 2018-12-13 04:58
Fix to this issue will be released in the next preview package, version `1.0.0-alpha.200`.

**Comment by SeanFeldman** [comment] 2018-12-13 05:19
New version `1.0.0-alpha0200` is available on [NuGet](1.0.0-alpha0200).

**Closed by SeanFeldman** 2018-12-13 05:19 UTC
